# Generated by Django 5.0.6 on 2024-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='original_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=100)),
                ('student_batch_name', models.CharField(max_length=255)),
                ('batch_name', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=100)),
                ('subject_type', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('obt_marks', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('obt_grade', models.CharField(max_length=2)),
                ('is_backlog', models.BooleanField()),
                ('is_pass', models.BooleanField()),
                ('backlog_attempt_number', models.IntegerField()),
                ('credit_point_earned', models.FloatField()),
                ('credit_point_offered', models.FloatField()),
                ('rv_marks', models.FloatField(blank=True, null=True)),
                ('rv_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
