# Generated by Django 5.0.6 on 2024-07-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_original_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='original_data',
            new_name='OriginalData',
        ),
    ]
