# Generated by Django 5.0.6 on 2024-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_rename_original_data_originaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldata',
            name='backlog_attempt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='credit_point_earned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='credit_point_offered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='exam_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='exam_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='is_backlog',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='is_pass',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='max_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='obt_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='obt_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='rv_updated',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='student_batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='subject_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='subject_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
