# Generated by Django 5.0.6 on 2024-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_alter_originaldata_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldata',
            name='course_category',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2),
        ),
    ]
