# Generated by Django 5.0.6 on 2024-07-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_alter_originaldata_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='course_category',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='Default Report Name', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='report_name',
            field=models.CharField(default='Default Report Name', max_length=255),
        ),
    ]
