# Generated by Django 5.0.6 on 2024-07-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_uploadedfile_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='report_name',
        ),
    ]
