# Generated by Django 5.0.6 on 2024-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_remove_uploadedfile_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originaldata',
            name='course_category',
            field=models.CharField(choices=[('UG', 'PG')], max_length=2),
        ),
    ]
